import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/Provider/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vend Crunch",
  description: "Generated by create next app",
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple: ['/apple-touch-icon.png?v=4'],
    shortcut: ['/apple-touch-icon.png'],
  },
  manifest: '/site.webmanifest'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
            {children}
        </AuthProvider>

      </body>

    </html>
  );
}
